'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace AddOnInstaller

    Public Class AddOnInstallInfo

        Public StrAddOnInstallPath As String

        Public AddOnName As String

        Public PartnerName As String

        Public ExeFile As String

        Public DIFile As String

        Public UIFile As String

        Public B1WizardBaseFile As String

        Public ExtraFiles As System.String()

        Public ExtraDirectories As System.String()

        Public RestartNeeded As Boolean

        Public Sub New()
            MyBase.New()
            PartnerName = "UPD"
            RestartNeeded = False

            'ATENÇÃO: Este é o nome do addon no painel de addons do SAP - nome do ARD
            'AddOnName = "TESTES - Business Flow Administracao"
            'AddOnName = "TESTES - Business Flow Integrador"
            AddOnName = "Contratos Cafebras"

            'ATENÇÃO: Este é o executável do addon !!!NÃO DÊ O MESMO NOME AO .ARD OU VC TERÁ ERRO DE ASSINATURA AO INSTALAR O ADDON!!!
            'ExeFile = "BusinessFlow.exe"
            ExeFile = "CafebrasContratos.exe"

            'ATENÇÃO: Após remover e re-acrescentar os arquivos na pasta AddonFiles, faça:
            '             1) Selecione todos os arquivos;
            '             2) Clique com o botão direito em Propriedades;
            '             3) Defina "Build Action" para "Embedded Resource";
            '         Se esse passo não for executado, o instalador gerado terá apenas 50kb 
            '         e não terá levado os arquivos necessários para dentro dele.
            DIFile = "Interop.SAPbobsCOM.dll"
            UIFile = "Interop.SAPbouiCOM.dll"

            ExtraFiles = New String() {
                "criar_menus.xml",
                "FormCertificado.srf",
                "FormConfiguracaoPeneira.srf",
                "FormContratoFinal.srf",
                "FormContratoFinalAberturaPorPeneira.srf",
                "FormContratoFinalComissoes.srf",
                "FormContratoFinalDetalheCertificado.srf",
                "FormGrupoDeItens.srf",
                "FormMetodoFinanceiro.srf",
                "FormModalidade.srf",
                "FormParticipante.srf",
                "FormPreContrato.srf",
                "FormPreContratoAberturaPorPeneira.srf",
                "FormPreContratoComissoes.srf",
                "FormPreContratoDetalheCertificado.srf",
                "FormSafra.srf",
                "FormSelecaoDocMKT.srf",
                "FormTipoOperacao.srf",
                "FormUnidadeComercial.srf",
                "FormUtilizacaoBloqueada.srf",
                "logo.png",
                "remover_menus.xml",
                "SAPHelper.dll"
            }

            ExtraDirectories = New String() {""}

        End Sub
    End Class
End Namespace
